# Generated by Django 5.1.1 on 2024-11-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacherTasksLogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='apply',
            field=models.BooleanField(default=False),
        ),
    ]
