# Generated by Django 5.1.1 on 2024-11-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacherTasksLogic', '0002_task_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
