# Generated by Django 5.1.1 on 2024-11-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacherTasksLogic', '0003_alter_task_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_expired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
