# Generated by Django 5.1.1 on 2024-11-26 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacherTasksLogic', '0004_alter_task_date_alter_task_date_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_expired',
            field=models.DateField(default=datetime.datetime(2099, 12, 31, 0, 0)),
        ),
    ]
