# Generated by Django 5.1.1 on 2024-11-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacherTasksLogic', '0005_alter_task_date_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='check_phrases',
            field=models.BooleanField(default=False),
        ),
    ]
