# Generated by Django 5.1.1 on 2024-12-01 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacherTasksLogic', '0006_task_check_phrases'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='students_passed',
            field=models.ManyToManyField(related_name='students_pass', to=settings.AUTH_USER_MODEL),
        ),
    ]
