# Generated by Django 5.1.1 on 2024-12-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teacherTasksLogic', '0007_task_students_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remove_punctuation',
            field=models.BooleanField(default=True),
        ),
    ]
