# Generated by Django 5.1.1 on 2024-10-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_to_children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('child_id', models.IntegerField()),
                ('question', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestSentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_request', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100000)),
                ('text_clear', models.CharField(max_length=100000)),
                ('len', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('count', models.IntegerField(default=1)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
