# Generated by Django 5.0.7 on 2024-09-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysSentenceLogic', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='tokens',
        ),
        migrations.AddField(
            model_name='sentence',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
