# Generated by Django 5.1.1 on 2024-10-19 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analysSentenceLogic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestsentences',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
