# Generated by Django 5.0.7 on 2024-09-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysSentenceLogic', '0003_remove_sentence_tokens_sentence_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='image',
        ),
    ]
