# Generated by Django 5.0.7 on 2024-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysSentenceLogic', '0005_alter_sentence_data_delete_sentence_to_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestSentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_request', models.CharField(max_length=50)),
                ('request_sentences', models.ManyToManyField(related_name='query_sentences', to='analysSentenceLogic.sentence')),
            ],
        ),
    ]
