# Generated by Django 5.0.7 on 2024-09-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogic', '0002_correctuser_change_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctuser',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
