# Generated by Django 5.1.1 on 2024-12-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('studentTasksLogic', '0004_remove_tasksentences_check_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('task', models.IntegerField()),
                ('result_check', models.JSONField(blank=True)),
                ('sentences', models.ManyToManyField(related_name='sentences', to='studentTasksLogic.tasksentences')),
            ],
        ),
    ]
