# Generated by Django 5.1.1 on 2024-12-07 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('studentTasksLogic', '0008_alter_studenttask_result_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttask',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
