# Generated by Django 5.0.7 on 2024-07-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=3000)),
                ('len', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tokens', models.JSONField()),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_in_sentence', models.IntegerField()),
                ('text', models.CharField(max_length=3000)),
                ('head_text', models.CharField(max_length=3000)),
                ('len', models.IntegerField()),
                ('head_id', models.IntegerField(blank=True)),
                ('pos', models.CharField(max_length=10)),
                ('dep', models.CharField(default='none', max_length=10)),
                ('children', models.JSONField()),
            ],
        ),
    ]
